### ISSUE TITLE
Networking en Linkedin

### ISSUE THREAD

**Issue by piagomez** [programadoreschile/sugerencias#1]
Generar comunidad en linkedin, para aumentar las oportunidades laborales.

**Comment by kevinzeladacl** [comment]
¿Dices crear un grupo oficial en Linkedin? o ¿Tienes otra idea?

**Comment by kevinzeladacl** [comment]
Estimados, se creo el grupo https://www.linkedin.com/grp/home?gid=8352587 ya que a eso iba la sugerencia. También se creo debido a la recepción del post en el grupo en facebook donde muchos compartían sus linkedin pero varios eran contactos en 3er grado. El grupo los une y facilita la comunicación.
