### ISSUE TITLE
Clases Presenciales "Programadores Chile"

### ISSUE THREAD

**Issue by kevinzeladacl** [programadoreschile/sugerencias#3]
Post de referencia: https://www.facebook.com/groups/Programadores.Chile/permalink/1507734916183146/

*POR FAVOR LEER*
===================
**Los que quieran participar y ayudar que dejen su correo aquí para armar una grupo slack/chat/algo y empezar a organizar todo.**

**Comment by LestatAlmasy** [comment]
c.orellanavargas@uandresbello.edu Comenté en el grupo igual que me estaba consiguiendo salas en mi universidad (Unab, sede Antonio Varas, Providencia) y estoy generando un documento igual para ordenar la forma de dictar clases. Saludos!

**Comment by kevinzeladacl** [comment]
Anotado, esperando a más interesados hasta el viernes a las 20:00 hrs.

**Comment by patojimenez** [comment]
developer.jimenez@gmail.com voy a ver si me puedo conseguir las oficinas nuevas de Start-Up Chile o el CMI. :)

**Comment by jonjetli** [comment]
Yo me puedo conseguir el agora de wayra telefónica en santiago , una consulta esto será solo para santiago en primera instancia o se puede extrapolar para regiones como valparaiso/viña??

Ya que me puedo conseguir también en valpo/viña

**Comment by diogenessm** [comment]
El condominio en el que vivo cuenta con una gran sala de eventos, la cual podría conseguir para la actividad, les enviaré fotos. diogenes.sazo@gmail.com,

**Comment by kevinzeladacl** [comment]
@jonjetli  sería excelente si puede ser igual en regiones, así vamos descentralizando la comunidad :+1: 

Voy a esperar al domingo y luego cierro esto para ya empezar a organizar con los interesados :100: 

Bkn que se motiven.

**Comment by taoman** [comment]
Bump.

**Comment by AlexVilla** [comment]
Alex.villa.v@gmail.com puedo hablar en la universidad San Sebastian, si se logran hacer buenas cantidades de gente (y supongo que la u pedirá que los alumnos puedan ir) hasta más de algo podemos sacar, laboratorios, comida o algo así, pero depende de lo que se necesite y lo que se pida

**Comment by kevinzeladacl** [comment]
Chicos creare un chat o un slack junto todos los interesados para empezar ya a organizar esto.

**Comment by kevinzeladacl** [comment]
Les envíe un correo a todos con los pasos a seguir :+1:  Saludos.

**Comment by dmunozgaete** [comment]
@kevinzeladacl , reenviarme el correo , que quede un poco fuera de los plazos !, 

Saludos y  podamos realizar esta sugerencia!.

**Comment by AlexVilla** [comment]
A mi no me ha llegado nada

El vie, ago 7, 2015 05:18 PM, David Gaete <notifications@github.com>
escribió:

> @kevinzeladacl <https://github.com/kevinzeladacl> , reenviarme el correo
> , que quede un poco fuera de los plazos !,
>
> Saludos y podamos realizar esta sugerencia!.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/programadoreschile/sugerencias/issues/3#issuecomment-128824331>
> .
>
-- 

*Alex Villa*

* Estudiante Ingeniería Civil Informática   Universidad San Sebastián*
*avillav@correo.uss.clalex.villa.v@gmail.com*
* Tel: (56 9) 844 183 99*

**Comment by kevinzeladacl** [comment]
@AlexVilla , pero si has participado de los correos, de todas formas envié sumando a los que faltan.

**Comment by AlexVilla** [comment]
Jajajajaja lo siento fue un error de lectura, pensé que ya habían fijado el
lugar y no me había llegado eso, perdón!

El vie, ago 7, 2015 06:16 PM, Kevin Zelada <notifications@github.com>
escribió:

> @AlexVilla <https://github.com/AlexVilla> , pero si has participado de
> los correos, de todas formas envié sumando a los que faltan.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/programadoreschile/sugerencias/issues/3#issuecomment-128835842>
> .
>
-- 

*Alex Villa*

* Estudiante Ingeniería Civil Informática   Universidad San Sebastián*
*avillav@correo.uss.clalex.villa.v@gmail.com*
* Tel: (56 9) 844 183 99*

**Comment by kevinzeladacl** [comment]
@AlexVilla no, es imperdonable como es posible tal confusión...jajaja na compadre relax a cualquiera le pasa (a mi frecuentemente) :dancers: bailarinas para todos :v:

**Comment by taoman** [comment]
Hola, en qué estado está esto? Creo que no he recibido ningún correo con pasos a seguir. Me interesa. Saludos.
