### ISSUE TITLE
Charlas Presenciales y Cursos para la comunidad

### ISSUE THREAD

**Issue by dmunozgaete** [programadoreschile/sugerencias#6]
## Charlas Presenciales y cursos progresivos para conocernos un poco mas y compartir ideas

Me gustaría proponer una sección de cursos y talleres mas personalizados sobre los principales tópicos en los cuales se mueve la comunidad.

Como no me gusta proponer sin apoyar, les ofrezco actualmente mis dependencias , es una empresa con alrededor 50 mts utiles donde podremos coordinar y realizar meetups o charlas de algunos tópicos populares.

Propongo ademas la primera charla , sobre angularJS  y Restful (para partir por lo basico) , y luego ir subiendo el nivel en charlas sucesivas.

Por mi parte me gustaría una charla sobre trabajo en GIt, por lo que he visto  hay muchos miembros que se manejan bastante sobre esto , y en mi caso particular,  me gustaría saber mas , y que mejor que venga de las personas dentro de  la comunidad. 

__BTW__: Nuestra [oficinas](https://www.google.cl/maps/place/Nueva+de+Lyon+96,+Providencia,+Regi%C3%B3n+Metropolitana/data=!4m2!3m1!1s0x9662cf6631efef27:0x219a553f602e447?sa=X&ved=0CBwQ8gEwAGoVChMImNKokdWXxwIVC5SQCh2rJQUj) se encuentran en providencia , cerca del portal lyon

Saludos y espero sus opiniones.

**Comment by kevinzeladacl** [comment]
Estimado, esto ya se esta coordinando, si puedes prestar tus oficinas envíame un correo a yo@kevinzelaa.cl para unirte al hilo de la discusión.

Anterior sugerencia : https://github.com/programadoreschile/sugerencias/issues/3

**Comment by dmunozgaete** [comment]
Aki va mi correo. (por si acaso xD: dmunoz@valentys.com<mailto:dmunoz@valentys.com>)



Saludos!.

[cid:877415AE-8682-4A3F-9A86-0624AC01BF15]<http://www.valentys.com>


En 7 de agosto de 2015 en 16:18:15, Kevin Zelada (notifications@github.com<mailto:notifications@github.com>) escrito:

yo@kevinzelaa.cl<mailto:yo@kevinzelaa.cl>
