### ISSUE TITLE
Manejar proyectos Open source de la comunidad

### ISSUE THREAD

**Issue by YerkoPalma** [programadoreschile/sugerencias#7]
Hace tiempo pensaba en que como comunidad se han desarrollado pocos o ningún proyectos. Propongo crear un mecanismo para postular y desarrollar proyectos open source de la comunidad y luego publicarlos bajo el dominio www.programadoreschile.cl

## Mecanismo

El envío de proyectos debe apegarse a ciertas reglas basicas:

* **Todos** los proyectos que se publiquen son open source (determinar la licencia que aplica)
* Los proyectos deben proporcionar los siguientes datos

    | Dato  | Descripción |
    | ------------- | ------------- |
    | Nombre proyecto  | Nombre del proyecto  |
    | Estado  | Estado actual del proyecto. Puede ser `en evaluación`, `en desarrollo`, `en pruebas`. Si esta `en evaluación` aún no se sabe la duración ni la cantidad d desarrolles necesitados, por lo que el autor de la idea debe ser orientado o por toda la comunidad o por los admins del grupo o un grupo de desarrolladores determinado por la comunidad o los admins   |
    | Duración  | Puede ser en meses o semanas  |
    | Tecnología  | Indicaciones detalladas de frameworks y lenguajes, ya que determinaran la infraestructura necesaria y las habilidades requeridas de los desarrolladores  |
    | Número de desarrolladores  | Debe ser aprobado previmente por la comunidad o los admins  |
    | Modalidad  | Puede ser: `freelance`, `semi-precencial` o `presencial`. En caso de ser presencial, quien proponga la idea debe justificar la modalidad y ofrecer un punto de encuentro para los desarrolladores  |

* Los medios de publicación de las solicitudes de proyectos, serán determinados por los admins de la comunidad
* En caso de ofrecerse más desarrolladores de los necesitados, se debe determinar un mecanismo de selección de los mismos
* Al momento de publicar se debe respetar la autoria del grupo desarrollador.

## Posibles problemas

Existen quizas más problemas de los enumerados acá, pero por ahora, lo más evidente es lo siguiente:

* Monetario (?): Seguramente se recibiran postulaciones para distintas tecnologías, y seguramente no se tiene servidores para cada una de estas arquitecturas, entonces se debiese hacer un esfuerzo por conseguir fondos para tener servidores en las principales tecnologias de desarrollo. Propongo inicialmente tener soporte para `php`, `node.js`, `Ruby on Rails`, `java` 

## Ejemplo

Como creo que esto debiese funcionar sería de la siguiente manera: Supongamos alguien hace una solicitud para un proyecto llamado **`msn`** el proyecto esta completamente diseñado solo falta empezar el desarrollo, por lo tanto el estado sería **`en desarrollo`** se calcula su duración en **`6 meses`** y quien lo propone dice necesitar **5 desarrolladores**. La comunidad o los admin lo reevaluan y dicen que se necesitan en verdad solo **4 desarrolladores**. Se desarrolla el proyecto de forma semipresencial en **`java`**, el grupo se reune una vez cada dos semanas fisicamente y por skype regularmente. Una vez terminado, se publica en el github de la comunidad el código, y en la dirección www.programadoreschile.cl/proyectos/msn, con referencia al perfil en linkedin de los desarrolladores

**Comment by kevinzeladacl** [comment]
Mis observaciones:

1 - **Duración** :  Debe tener un plazo fijo de lanzamiento (ej: 2 meses maximo) y luego puede continuar su desarrollo, pero debe ser lanzado en ese plazo. De esta forma podemos controlar que no se llene de proyectos abiertos y descontinuados. Si no se lanza en dicho limite el proyecto pasa a "descontinuado"

2 - **N° Desarrolladores** : Estos debe proponerlos el "jefe de proyecto" (Por defecto quien postula la iniciativa), es decir del debe estimar cuantos necesita como MIN o MAX. En base a eso acepta o no desarrolladores que cumplan con lo que necesita.

3 - **Modaliad** :  Aquí pueden ser **Presencial** o **Remota**, la frecuencia de esta depende de lo que proponga quien postula la idea y deben organizarse internamente. Freelance da a interpretar otra cosa.

4- **El problema monetario** :  Para el lanzamiento de dicha app se hará un evento o se juntan varias app y se organiza un evento para financiar los servidores. Esto no es tan complejo solo se debe organizar bien, el staff se preocupara de esto y se tratara con cada equipo independientemente.

5- **Pasos Formales** : Esto no es muy complicado solo abrir en el sitio web un formulario para postular la idea o en un repo en github. Luego solo se debe buscar equipo, en fin esta parte la hablaremos en el **STAFF** y propondremos algo bueno y transparente.


Mis comentarios generales es que esta super buena la sugerencia y no veo problemas en hacer esto oficial pronto. Daremos unos días más para recibir feedback de la comunidad y empezaremos a consolidarlo como oficial.

**Comment by YerkoPalma** [comment]
Me gusto la idea de generar eventos, de preferencia periodicos, en los que se lanzen las apps que se desarrollen en la comunidad.

Discutanlo, y ojala si llegan a consenso y les gusta se anuncie con bombos y platillos, para empezar a proponer ideas.

**Comment by kevinzeladacl** [comment]
Estoy pasando esto a normas y pautas @YerkoPalma 

En un rato o en la noche esta :ghost:
