### ISSUE TITLE
Pauta para oferta de proyectos.

### ISSUE THREAD

**Issue by cl-ar** [programadoreschile/sugerencias#8]
Creo que el formato para Oferta Laboral, no es suficiente para este tipo de ofertas (proyectos).
Estas ofertas podrían incluir unos requerimientos definidos, opcionalmente agregar un ejemplo. 
También incluir un rango a pagar, ya que siempre se las sacan con "que es relativo".

**Comment by kevinzeladacl** [comment]
Manda un pull request :+1:  con tus sugerencias
